#!/bin/bash

   case "${1:-''}" in

      'start')
      if test -f /tmp/selenium.pid
      then
         echo "Selenium is already running."
      else
         echo "Starting Selenium ..."
         export DISPLAY=localhost:99.0
         /usr/bin/java -jar /usr/local/lib/selenium-server-standalone-2.47.1.jar -port 5555 -Dwebdriver.firefox.bin=/usr/local/bin/firefox -trustAllSSLCertificates > /var/log/selenium/output.log 2> /var/log/selenium/error.log & echo $! > /tmp/selenium.pid
         error=$?
         if test $error -gt 0
         then
            echo "Error $error! Couldn't start Selenium!"
         fi
      fi
      ;;

   'stop')
      if test -f /tmp/selenium.pid
      then
         echo "Stopping Selenium ..."
         PID=`cat /tmp/selenium.pid`
         kill -3 $PID
         if kill -9 $PID ;
         then
            sleep 2
            test -f /tmp/selenium.pid && rm -f /tmp/selenium.pid
         else
            echo "Selenium could not be stopped ..."
         fi
      else
         echo "Selenium is not running."
      fi
   ;;

   'restart')
      $0 stop
      $0 start
   ;;

   'status')
      SELENIUM_STATUS=`ps -C java -o pid,cmd | grep '5555' | awk '{ print $1 }'`
      if [ ! -f $SELENIUM_STATUS ]
      then
         PID=`ps -C java -o pid,cmd | grep '5555' | awk '{ print $1 }'`
         echo "Selenium is running: PID ${PID}"
      else
         echo "Selenium isn't running ..."
      fi
   ;;

   *) # no parameter specified
      echo "Usage: $SELF start|stop|restart|status"
      exit 1
   ;;
   esac
